name: ripple_button
description: A fully customizable button with material ripple effect. Easy to use having some pre-defined button types.
repository: https://github.com/lcsvcn/ripple_button.git
homepage: https://github.com/lcsvcn/ripple_button.git
version: 2.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
