name: Widget tests & code analysis

on: [push, pull_request]

# https://admcpr.com/continuous-integration-for-flutter-with-github-actions/
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # Use the community Action to install Flutter
    - uses: subosito/flutter-action@v1
    - name: Version
      run: flutter doctor -v
    - name: Install dependencies
      run: flutter pub get
    - name: Format
      run: flutter format -n --set-exit-if-changed .
    - name: Linter
      run: flutter analyze
    # - name: Test
    #   run: flutter test
